# Build pipeline for publishing

trigger:
  batch: true
  branches:
    include:
      - main
      - releases/*

pr: none

parameters:
  - name: skipNpmPublish
    displayName: Skip Npm Publish
    type: boolean
    default: true
  - name: skipGitPush
    displayName: Skip Git Push
    type: boolean
    default: true
  - name: skipNugetPublish
    displayName: Skip Nuget Publish
    type: boolean
    default: true

variables:
  - group: 'FluentUI React Native Secrets'
  - group: InfoSec-SecurityResults
  - name: tags
    value: production,externalfacing
  - template: variables/vars.yml

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    stages:
      - stage: main
        jobs:
          - job: NPMPublish
            displayName: NPM Publish
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(System.DefaultWorkingDirectory)
                  artifactName: dist
            steps:
              - template: .ado/templates/setup-repo.yml@self

              - script: |
                  git config user.name "UI-Fabric-RN-Bot"
                  git config user.email "uifrnbot@microsoft.com"
                  git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/ui-fabric-react-native.git
                displayName: Git Authentication

              - script: |
                  yarn
                displayName: 'yarn install'

              - script: |
                  yarn buildci
                displayName: 'yarn buildci'

              - script: |
                  echo ##vso[task.setvariable variable=SkipNpmPublishArgs]--no-publish
                displayName: Enable No-Publish (npm)
                condition: ${{ parameters.skipNpmPublish }}

              - script: |
                  echo ##vso[task.setvariable variable=SkipGitPushPublishArgs]--no-push
                displayName: Enable No-Publish (git)
                condition: ${{ parameters.skipGitPush }}

              - script: |
                  yarn publish:beachball $(SkipNpmPublishArgs) $(SkipGitPushPublishArgs) --access public --token $(npmAuth) -b origin/main -y
                displayName: 'Publish NPM Packages (for main branch)'
                condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

              - script: |
                  yarn publish:beachball $(SkipNpmPublishArgs) $(SkipGitPushPublishArgs) --access public --token $(npmAuth) -y -t v${{ replace(variables['Build.SourceBranch'],'refs/heads/releases/','') }} -b origin/${{ replace(variables['Build.SourceBranch'],'refs/heads/','') }} --prerelease-prefix ${{ replace(variables['Build.SourceBranch'],'refs/heads/releases/','') }}
                displayName: 'Publish NPM Packages (for other release branches)'
                condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

          - template: .ado/templates/apple-nuget-publish.yml@self
            parameters:
              skipNugetPublish: ${{ parameters.skipNugetPublish }}

          - template: .ado/templates/win32-nuget-publish.yml@self
            parameters:
              skipNugetPublish: ${{ parameters.skipNugetPublish }}

          - job: Win32TestingDependenciesNuGetPublish
            displayName: Win32 Automated Testing Dependencies NuGet Publish
            timeoutInMinutes: 90 # how long to run the job before automatically cancelling
            cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

            steps:
              - template: .ado/templates/e2e-dependency-nuget-publish.yml@self
                parameters:
                  skipNugetPublish: ${{ parameters.skipNugetPublish }}
